### 21장. 셈하기 
### **수집한 결과를 출력하기**
- 테스트 메서드에서 예외가 발생하건 말건 tearDown()이 호출되도록 보장해주는 기능을 구현하려고 했다. 
- 하지만 테스트가 작동하도록 하려면 예외를 잡아야한다. 
- 만약 이 기능을 구현하다가 실수하면 예외가 보고되지 않기 때문에 실수를 알아챌 방법이 없다. 
- 일반적으로 **테스트를 구현하는 순서**는 중요하다. 
- 다음으로 구현할 테스트를 선택할 때, 가르침을 줄 수 있고 내가 만들 수 있다는 확신이 드는 것을 선택한다. 
- 모든 테스트가 성공하던 매시점을 일종의 체크 포인트로 하여 임의로 되돌릴 수 있도록 프로그래밍 환경이 지원한다면 아주 좋을 것이다. 
- 여러 테스트를 실행하고 그 결과를 다음과 같이 보길 원한다. 
  - "5개 테스트가 실행됨, 2개 실패, TestCaseTest.testFooBar-ZeroDivide Exception, MoneyTest.testNegation-AssertionError"
- TestCase.run()이 테스트 하나의 실행 결과를 기록하는 TestResult 객체를 반환하게 만들 것이다. 

```python
# TestCaseTest
def testResult(self):
    test = WasRun("testMethod")
    result = test.run()
    assert("1 run, 0 failed" == restult.summary())
# 가짜구현 시작하기
# TestResult.py
class TestResult:
    def summary(self):
        return "1 run, 0 failed"
# TestCase.run()이 TestResult를 결과로 반환한다. 
# TestCase.py
def run(self):
    self.setUp()
    method = getattr(self.self.name)
    method()
    self.tearDown()
    return TestResult()
```
- 이제 테스트가 실행된다. 이제 summary()의 구현을 조금씩 진짜 구현할 수 있다. 
- 우선 실행된 테스트의 수를 상수로 만들 수 있다. 
```python
# TestResult
def __init__(self):
    self.runCount = 1
def summary(self):
    return "%d run, 0 failed" % self.runCount
```
- runCount를 0으로 초기화하고 테스트가 실행될 때마다 1씩 증가시키게 만들 수 있다. 
```python
# TestResult
def __init__(self):
    self.runCount = 0
def testStarted(self):
    self.runCount = self.runCount + 1
def summary(self):
    return "%d run, 0 failed" % self.runCount
```

- 이제 새 testStarted 메서드를 실제로 호출하게 만들어야한다. 
```python
# TestCase.py
def run(self):
    result = TestResult()
    result.testStarted()
    self.setUp()
    method = getattr(self, self.name)
    method()
    self.tearDown()
    return result
```
- 실패하는 테스트의 수를 나타내는 문자열 상수 '0'을 runCount를 실체화했을 때와 마찬가지의 방법을 통해 변수로 만들수 있겠지만 이 작업을 하게끔 만들어주는 테스트가 존재하지 않는다.
- 테스트를 작성하자
```python
# TestCaseTest
def testFailedResult(self):
    test = WasRun("testBrokenMethod")
    result = test.run()
    assert("1 run, 1 failed" == result.summary())

# WasRun.py
def testBrokenMethod(self):
    raise Exception
```
- 우리가 관심을 가져야 할 사항은 WasRun.testBrokenMethod에서 던진 **예외를 처리하지 않았다**는 점이다. 
- 예외를 잡고 테스트가 실패했음을 테스트 결과에 적어 넣고 싶지만 잠시 동안 할일 목록에 남겨두자.

### 한 작업 검토
1. 가짜 구현을 한 뒤에 단계적으로 상수를 변수로 바꾸어 실제 구현으로 만들었다. 
2. 또 다른 테스트를 작성했다. 
3. 테스트가 실패했을 때 좀더 작은 스케일로 또 다른 테스트를 만들어서 실패한 테스트가 성공하게 만드는 것을 보조 할 수 있었다. 
